### ISSUE TITLE
Close this repo or make it a linked submodule?

### ISSUE THREAD

**Issue by ryanttb** [LibraryBox-Dev/LibraryBox-landingpage#3]
It seems there is now a copy in core ( LibraryBox-Dev/LibraryBox-core/tree/development/LibraryBox-landingpage ) which is more actively being developed. It's confusing as to which one we should edit.

However, if you'd like the landing page to have its own repo, issues, & pull requests, make it a submodule:
http://stackoverflow.com/a/5205785/993890

**Comment by MaStr** [comment]
It is already a git-subtree on LibraryBox-core and we remove this repository now.
